services:
  app:
    build:
      args:
        user: node
        uid: 1000
        gid: 1000
      context: .
      dockerfile: Node.dockerfile
      target: 'dev-stage'
    ports:
      - '3000:3000'
    container_name: apinodejs-app
    restart: always
    #command: /bin/sh -c "chown -R 1000:1000 /app && cd /app && npm i && node src/app.js"
    command: /bin/sh -c "chown -R 1000:1000 /app && cd /app && npm i && npm start"
    volumes:
      - './app:/app'
    networks:
      - apinodejs
  db:
    image: mariadb:11
    container_name: apinodejs-db
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_USER: 'efmadm'
      MYSQL_PASSWORD: 'edu123456'
      MYSQL_DATABASE: 'cac2024'
    volumes:
      - ./sqldata:/var/lib/mysql
    networks:
      - apinodejs
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: apinodejs-admin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: 'root'
      PMA_PASSWORD: 'rootpass'
      UPLOAD_LIMIT: 64M
    links:
      - db
    ports:
      - "8080:80"
    networks:
      - apinodejs

networks:
  apinodejs:
      name: apinodejs_net